<a href="https://colab.research.google.com/github/sjungmin98/study_AIs/blob/main/docs/MLs/classfications/01_LogisitcRegression_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 분류 모델

### 데이터

In [7]:
from sklearn.datasets import load_iris
iris_X, iris_y = load_iris(return_X_y=True)

In [9]:
type(iris_X), type(iris_y), iris_X.shape, iris_y.shape

(numpy.ndarray, numpy.ndarray, (150, 4), (150,))

In [11]:
iris_X[:3], iris_X[-3:] # X, features

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([[6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]))

In [13]:
iris_y[:3], iris_y[-3:]

(array([0, 0, 0]), array([2, 2, 2]))

## 모델 선택과 학습

In [34]:
import sklearn.linear_model

In [40]:
logistic_Regression = sklearn.linear_model.LogisticRegression()
logistic_Regression

LogisticRegression()

In [42]:
logistic_Regression.fit(iris_X, iris_y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
logistic_Regression.predict(iris_X[:3])

array([0, 0, 0])

In [54]:
logistic_Regression.predict(iris_X[-3:])

array([2, 2, 2])

### 학습 방식 확인

In [56]:
logistic_Regression.predict(iris_X[:1])

array([0])

In [57]:
logistic_Regression.predict_proba(iris_X[:1])

array([[9.81799409e-01, 1.82005762e-02, 1.43509289e-08]])